<h2>Přihlášení</h2>

<div class="form">
<form method="POST" enctype="multipart/form-data">
    <div class="uname">
        <label for="username">Uživatelské jméno</label>
        <input type="text" name="username" id="username">
    </div>
    <div class="pass">
        <label for="password">Heslo</label>
        <input type="password" name="password" id="password">
    </div>

    <button name="logForm"><strong>Přihlásit se</strong></button>
</form>
</div>