<h2>Přidání nového úložného prostoru</h2>

<form method="POST">
    <div class="storage-wide">
        <div class="row">
            <input type="text" name="radaRacku" id="radaRacku" placeholder="Řada racků" required>
        </div>
        <div class="inRow">
            <input type="text" name="cisloRacku" id="cisloRacku" placeholder="Číslo racku" required>
        </div>
        <button name="storageForm">Přidat</button>
    </div>
</form>