<?php
    $today = date('Y-m-d');
?>

<h2>Přidání nového záznamu</h2>
<form method="POST">
    <div class="form-wide">
        <label for="poradCislo">Pořadové číslo</label>
        <input type="text" name="poradCislo" id="poradCislo" required>

        <label for="char1">Spisový znak</label>
        <input type="text" name="char1" id="char1" required>
        
        <label for="name">Název</label>
        <input type="text" id="name" name="name" required>

        <label for="date">Datum uložení</label>
        <input type="date" name="date" id="date" value="<?php echo $today ?>" required>

        <label for="char2">Skartovací znak</label>
        <select name="char2" id="char2">
            <option value="0" selected disabled>--Vyberte znak--</option>
            <option value="S1">S1</option>
            <option value="S2">S2</option>
            <option value="S3">S3</option>
            <option value="S4">S4</option>
            <option value="S5">S5</option>
        </select>
        

        <label for="yearSkart">Rok skartace</label>
        <input type="text" name="yearSkart" id="yearSkart" readonly placeholder="Zadejte znak...">
        <script>
            document.getElementById('char2').addEventListener('input', function () {
                const value = this.value;
                fetch('process.php', {
                    method: 'POST',
                    headers: {'Content-Type': 'application/x-www-form-urlencoded'},
                    body: 'input1=' + encodeURIComponent(value)
                })
                .then(response => response.text())
                .then(data => {
                    document.getElementById('yearSkart').value = data;
                });
            });
        </script>

        <label for="row">Řada</label>
        <select name="row" id="row" required>
            <option value="" disabled selected>--Vyberte řadu--</option>
            <?php foreach($rows as $rowVal){ ?>
                <option value="<?= $rowVal ?>"><?= $rowVal ?></option>
            <?php } ?>
        </select>

        <label for="number">Číslo</label>
        <select name="number" id="number" required>
            <option value="" disabled selected>--Vyberte číslo--</option>
            <?php foreach($racks as $rackVal){ ?>
                <option value="<?= $rackVal ?>"><?= $rackVal ?></option>
            <?php } ?>
        </select>

        <button name="fileForm">Přidat</button>
    </div>
</form>
