<h2>Registrace</h2>

<?php if(isset($_GET["success"])) { ?>
    <div class='registerSuccess'><p>Úspěšně jste se zaregistrovali!<br>Nyní se můžete <a href='login.php'>přihlásit</a></p></div>
<?php } ?>

<div class="form">
<form method="POST" enctype="multipart/form-data">
    <div class="uname">
        <label for="username">Uživatelské jméno</label>
        <input type="text" name="username" id="username">
    </div>
    <div class="pass">
        <label for="password">Heslo</label>
        <input type="password" name="password" id="password">
    </div>
    <div class="pass">
        <label for="password2">Heslo znovu</label>
        <input type="password" name="password2" id="password2">
    </div>
    <div class="divEmail">
            <label for="email">E-mail</label>
            <input type="email" name="email" id="email">
    </div>

    <button name="regForm">Registrovat se</button>
</form>
</div>