<h2>Správa úložných prostor</h2>


<?php if(isset($_SESSION["loggedUser"]["is_admin"])){ ?>
    <div class="newStorage">
     <a href="new-storage.php">Nový úložný prostor</a>
    </div>
<?php } ?>

<div class="stul2">
    <table>
        <thead>
            <th>Řada racků</th>
            <th>Číslo racku</th>
            <?php if(isset($_SESSION["loggedUser"]["is_admin"])){ ?>
            <th class="actions">Akce</th>
            <?php } ?>
        </thead>
        <tbody>
            <?php
                foreach($racks as $rack){
            ?>
                <tr>
                    <td><?= $rack["radaRacku"] ?></td>
                    <td><?= $rack["cisloRacku"] ?></td>
                <?php if(isset($_SESSION["loggedUser"]["is_admin"])){ ?>
                    <td>
                        <form method="GET">
                            <input type="hidden" name="id" value="<?= $rack["ID"] ?>">
                            <button id="edit">Upravit</button>
                        </form>
                        <form method="POST">
                            <input type="hidden" name="id" value="<?= $rack["ID"] ?>">
                            <button name="deleteStorage">Odstranit</button>
                        </form>
                    </td>
                <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>