<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Archiver</title>
    <link rel="icon" type="image/x-icon" href="/image.svg">
    <link rel="stylesheet" type="text/css" href="/style.css">
</head>
<body>
    <header>
        <div class="head">
        <div class="titulek">
            <img src="./img/logo_white.svg" alt="Logo">
            <h1>Archiver</h1>
        </div>
        <?php if(!isset($_SESSION["loggedUser"])){ ?>
        <div class="reg">
            <a href="register.php"><strong>Registrace</strong></a>
        </div>
        <div class="log">
            <a href="login.php"><strong>Přihlášení</strong></a>
        </div>
        <?php } else {?>
            <div class="user">
            <div class="userInfo">
                <?= "Uživatel: " . $_SESSION["loggedUser"]["username"] ?>
            </div>
        <?php } if(isset($_SESSION["loggedUser"]["is_admin"])){?>
            <div class="admin">
                ADMIN
            </div>
        <?php } ?>
        <?php if(isset($_SESSION["loggedUser"])){ ?>
        </div>
        <div class="logout">
            <form action="logout.php">
             <button type="submit">Odhlásit se</button>
            </form>
        </div>
        <?php } ?>
        </div>
        <div class="garmin">
        <nav>
            <ul>
                <li><a href="index.php">Prohlížení záznamů</a></li>
                <li><a href="storage.php">Prohlížení úložných prostor</a></li>
                <!-- <li><a href="new-file.php">Nový záznam</a></li>
                <li><a href="new-storage.php">Nový úložný prostor</a></li> -->
                <li><a href="about-us.php">O nás</a></li>
            </ul>
        </nav>
        </div>
    </header>